version: '3'

services:
  wp:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./config/apache/certs:/etc/ssl/certs
      - ./config/apache/private:/etc/ssl/private
      - ./wp-app:/var/www/html # Full wordpress project
      - ./wp-init.sh:/usr/local/bin/apache2-custom.sh
      - ./wantsum-brewery-plugin/:/var/www/html/wp-content/plugins/wantsum-brewery-plugin
      - ./prevent-shipping-of-non-courier-products/:/var/www/html/wp-content/plugins/prevent-shipping-of-non-courier-products
      - ./wantsum-brewery-theme/:/var/www/html/wp-content/themes/wantsum-brewery
      - ./mu-plugins/:/var/www/html/wp-content/mu-plugins
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      WORDPRESS_ADMIN_EMAIL: "${ADMIN_EMAIL}"

    depends_on:
      - db
    links:
      - db
    command: "bash -c apache2-custom.sh"

# TODO - run chown www-data:www-data  -R * in image on at /var/www/html to ensure apache can write to wordpress install.

  wpcli:
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    depends_on:
      - db
      - wp

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - ${IP}:8080:80
    links:
      - db:db

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

  gulp:
    build: gulp-sass
    volumes:
      - ./gulp-sass/src:/site/src
      - ./wantsum-brewery-theme:/site/theme
    command: gulp --gulpfile src/gulpfile.js

volumes:
  db_data:
